In [28]:
import urllib.request
import pandas as pd
import csv

In [29]:
csv = pd.read_csv(r"C:\Users\Rene\Desktop\Library_Usage_Liste.csv")

In [30]:
csv.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,ADULT,1092,761,60 to 64 years,M6,Mission,July,2016,p,phone,False,2003,False,9.0
1,0,ADULT,0,0,20 to 24 years,P1,Park,None,None,z,email,True,2014,False,5.0
2,0,ADULT,31,22,25 to 34 years,S7,Sunset,April,2016,z,email,True,2010,False,4.0
3,0,ADULT,0,0,45 to 54 years,P1,Park,None,None,a,print,False,2016,True,NaN
4,0,ADULT,0,0,25 to 34 years,X,Main Library,None,None,z,email,True,2015,False,3.0

In [24]:
csv.keys()

Index(['Patron Type Code', 'Patron Type Definition', 'Total Checkouts',
       'Total Renewals', 'Age Range', 'Home Library Code',
       'Home Library Definition', 'Circulation Active Month',
       'Circulation Active Year', 'Notice Preference Code',
       'Notice Preference Definition', 'Provided Email Address',
       'Year Patron Registered', 'Outside of County', 'Supervisor District'],
      dtype='object')

In [25]:
print(csv)

        Patron Type Code Patron Type Definition  Total Checkouts  \
0                      0                  ADULT             1092
1                      0                  ADULT                0
2                      0                  ADULT               31
3                      0                  ADULT                0
4                      0                  ADULT                0
5                      0                  ADULT              126
6                      3                 SENIOR                0
7                      0                  ADULT             3002
8                      0                  ADULT                4
9                      0                  ADULT               20
10                     0                  ADULT                3
11                     0                  ADULT              102
12                     0                  ADULT                0
13                     0                  ADULT               45
14                     0                  ADULT               88
15                     0                  ADULT               22
16                     0                  ADULT                1
17                     0                  ADULT                0
18                     0                  ADULT                5
19                     4                WELCOME                0
20                     0                  ADULT                0
21                     0                  ADULT                0
22                     0                  ADULT                1
23                     0                  ADULT                0
24                     0                  ADULT               12
25                     0                  ADULT                0
26                     0                  ADULT                0
27                     0                  ADULT               13
28                     0                  ADULT                0
29                     0                  ADULT                3
...                  ...                    ...              ...
423418                 3                 SENIOR                6
423419                 0                  ADULT                0
423420                 1               JUVENILE                5
423421                 2            YOUNG ADULT             1277
423422                 2            YOUNG ADULT             3914
423423                 0                  ADULT             2592
423424                 3                 SENIOR                0
423425                 1               JUVENILE               21
423426                 1               JUVENILE              373
423427                 1               JUVENILE               42
423428                 3                 SENIOR              425
423429                 1               JUVENILE                0
423430                 2            YOUNG ADULT               42
423431                 3                 SENIOR                0
423432                 2            YOUNG ADULT                0
423433                 4                WELCOME                0
423434                 1               JUVENILE               10
423435                 2            YOUNG ADULT               17
423436                16    DIGITAL ACCESS CARD                0
423437                 1               JUVENILE                0
423438                 0                  ADULT                0
423439                 1               JUVENILE                0
423440                 2            YOUNG ADULT               42
423441                 3                 SENIOR             1812
423442                 2            YOUNG ADULT              608
423443                 0                  ADULT              291
423444                 0                  ADULT               15
423445                 5                  STAFF              208
423446                 0                  ADULT               26
423447                 1               JUVENILE                0

        Total Renewals          Age Range Home Library Code  \
0                  761     60 to 64 years                M6
1                    0     20 to 24 years                P1
2                   22     25 to 34 years                S7
3                    0     45 to 54 years                P1
4                    0     25 to 34 years                 X
5                   11     45 to 54 years                M2
6                    0     65 to 74 years                C2
7                 1689     25 to 34 years                P5
8                    0     25 to 34 years                C2
9                    0     25 to 34 years                S7
10                   1     60 to 64 years                A5
11                  31     25 to 34 years                M6
12                   0     25 to 34 years                P7
13                  11     25 to 34 years                P3
14                  64     35 to 44 years                A5
15                   6     45 to 54 years                M2
16                   0     60 to 64 years                 X
17                   0     45 to 54 years                M4
18                   1     25 to 34 years                A5
19                   0     35 to 44 years                M6
20                   0     35 to 44 years                P1
21                   0     25 to 34 years                M4
22                   0     60 to 64 years                 X
23                   0     35 to 44 years                P1
24                   0     45 to 54 years                S7
25                   0     25 to 34 years                P7
26                   0     35 to 44 years                A5
27                  12     25 to 34 years                N6
28                   0     35 to 44 years                P1
29                   0     25 to 34 years                O7
...                ...                ...               ...
423418               1  75 years and over                R3
423419               0     60 to 64 years                E7
423420               0     10 to 19 years                R3
423421             642     10 to 19 years                S7
423422             359     10 to 19 years                P5
423423             487     10 to 19 years                I5
423424               0  75 years and over                E9
423425               0       0 to 9 years                O7
423426             216       0 to 9 years                M6
423427               1       0 to 9 years                 X
423428             381  75 years and over                 X
423429               0       0 to 9 years                N4
423430              21     10 to 19 years                 X
423431               0  75 years and over                 X
423432               0     10 to 19 years                 X
423433               0     45 to 54 years                 X
423434               0       0 to 9 years                V3
423435               0     10 to 19 years                B2
423436               0     10 to 19 years                P1
423437               0       0 to 9 years                W4
423438               0     10 to 19 years                W4
423439               0       0 to 9 years                N4
423440              53     10 to 19 years                M4
423441               0  75 years and over                C2
423442             364     10 to 19 years                S7
423443              13     10 to 19 years                P5
423444              11     60 to 64 years                M8
423445              58       0 to 9 years                B4
423446               0     10 to 19 years                M6
423447               0       0 to 9 years                E7

                   Home Library Definition Circulation Active Month  \
0                                  Mission                     July
1                                     Park                     None
2                                   Sunset                    April
3                                     Park                     None
4                             Main Library                     None
5                                   Marina                  January
6                                Chinatown                     None
7                                  Portola                     July
8                                Chinatown                     July
9                                   Sunset                     June
10                                    Anza                     June
11                                 Mission                     June
12                                 Potrero                     None
13                                Parkside                      May
14                                    Anza                     July
15                                  Marina                      May
16                            Main Library                      May
17                                  Merced                     None
18                                    Anza                  January
19                                 Mission                     None
20                                    Park                     None
21                                  Merced                     None
22                            Main Library                     June
23                                    Park                     None
24                                  Sunset                     June
25                                 Potrero                     None
26                                    Anza                     None
27                             North Beach                 February
28                                    Park                     None
29                                  Ortega                   August
...                                    ...                      ...
423418                            Richmond                September
423419  Eureka Valley/Harvey Milk Memorial                     None
423420                            Richmond                     July
423421                              Sunset                     July
423422                             Portola                     July
423423                           Ingleside                  January
423424                           Excelsior                     None
423425                              Ortega                September
423426                             Mission                  October
423427                        Main Library                     July
423428                        Main Library                     July
423429              Noe Valley/Sally Brunn                     None
423430                        Main Library                September
423431                        Main Library                     None
423432                        Main Library                     None
423433                        Main Library                     None
423434                   Visitacion Valley                September
423435         Bayview/Linda Brooks-Burton                      May
423436                                Park                     None
423437                    Western Addition                     None
423438                    Western Addition                     None
423439              Noe Valley/Sally Brunn                     None
423440                              Merced                     June
423441                           Chinatown                     July
423442                              Sunset                     July
423443                             Portola                    March
423444                         Mission Bay                     July
423445                      Bernal Heights                     July
423446                             Mission                    April
423447  Eureka Valley/Harvey Milk Memorial                     None

       Circulation Active Year Notice Preference Code  \
0                         2016                      p
1                         None                      z
2                         2016                      z
3                         None                      a
4                         None                      z
5                         2016                      z
6                         None                      z
7                         2016                      p
8                         2014                      p
9                         2015                      z
10                        2016                      z
11                        2012                      z
12                        None                      z
13                        2016                      z
14                        2016                      z
15                        2016                      z
16                        2016                      z
17                        None                      z
18                        2012                      z
19                        None                      z
20                        None                      z
21                        None                      z
22                        2013                      z
23                        None                      z
24                        2014                      z
25                        None                      z
26                        None                      z
27                        2014                      z
28                        None                      z
29                        2015                      z
...                        ...                    ...
423418                    2015                      p
423419                    None                      p
423420                    2015                      z
423421                    2016                      p
423422                    2016                      p
423423                    2016                      p
423424                    None                      p
423425                    2015                      z
423426                    2014                      z
423427                    2016                      z
423428                    2016                      p
423429                    None                      z
423430                    2013                      z
423431                    None                      z
423432                    None                      a
423433                    None                      z
423434                    2015                      p
423435                    2015                      z
423436                    None                      z
423437                    None                      z
423438                    None                      z
423439                    None                      z
423440                    2014                      p
423441                    2016                      p
423442                    2016                      z
423443                    2015                      p
423444                    2016                      z
423445                    2016                      z
423446                    2015                      z
423447                    None                      a

       Notice Preference Definition  Provided Email Address  \
0                             phone                   False
1                             email                    True
2                             email                    True
3                             print                   False
4                             email                    True
5                             email                    True
6                             email                    True
7                             phone                    True
8                             phone                    True
9                             email                    True
10                            email                    True
11                            email                    True
12                            email                    True
13                            email                    True
14                            email                    True
15                            email                    True
16                            email                    True
17                            email                    True
18                            email                    True
19                            email                    True
20                            email                    True
21                            email                    True
22                            email                    True
23                            email                    True
24                            email                    True
25                            email                    True
26                            email                    True
27                            email                    True
28                            email                    True
29                            email                    True
...                             ...                     ...
423418                        phone                   False
423419                        phone                   False
423420                        email                    True
423421                        phone                   False
423422                        phone                   False
423423                        phone                   False
423424                        phone                   False
423425                        email                    True
423426                        email                    True
423427                        email                    True
423428                        phone                   False
423429                        email                    True
423430                        email                    True
423431                        email                    True
423432                        print                   False
423433                        email                    True
423434                        phone                   False
423435                        email                    True
423436                        email                    True
423437                        email                    True
423438                        email                    True
423439                        email                    True
423440                        phone                   False
423441                        phone                   False
423442                        email                    True
423443                        phone                   False
423444                        email                    True
423445                        email                    True
423446                        email                    True
423447                        print                   False

        Year Patron Registered  Outside of County  Supervisor District
0                         2003              False                  9.0
1                         2014              False                  5.0
2                         2010              False                  4.0
3                         2016               True                  NaN
4                         2015              False                  3.0
5                         2003              False                  2.0
6                         2015               True                  NaN
7                         2004              False                  9.0
8                         2014              False                  5.0
9                         2011              False                  7.0
10                        2013              False                  NaN
11                        2009              False                  9.0

In [26]:
#Fragestellung 1, Thema Seniorenaktiviät: Zeige mir alle Benutzer ab 75 Jahren die Ihren Bibliotheksausweis erneuert haben.

In [31]:
Senior = csv[csv["Age Range"] == "75 years and over"]
Bibliotheksausweis_Erneuerung = csv[csv["Total Renewals"] >= 1]
Senioren_Verlängerungen = pd.merge(Senior, Bibliotheksausweis_Erneuerung)
Senioren_Verlängerungen.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,3,SENIOR,838,415,75 years and over,N6,North Beach,July,2016,z,email,True,2003,False,NaN
1,3,SENIOR,65,15,75 years and over,E9,Excelsior,June,2016,p,phone,False,2003,False,11.0
2,3,SENIOR,122,7,75 years and over,P9,Presidio,April,2014,z,email,True,2011,False,2.0
3,3,SENIOR,222,16,75 years and over,P7,Potrero,July,2016,p,phone,True,2003,False,10.0
4,3,SENIOR,487,34,75 years and over,R3,Richmond,May,2015,z,email,True,2003,False,2.0

In [57]:
#Fragestellung 2 Thema Standortanaylse: Wie viele Ausleihen gab es von Nutzern in der Zentralbibliothek?

In [72]:
Zentralbibliothek = csv[csv["Home Library Definition"] == "Main Library"]
Ausleihen = csv[csv["Total Checkouts"] >= 1]
Zentralbibliothek_Ausleihen = pd.merge(Zentralbibliothek, Ausleihen)
Zentralbibliothek_Ausleihen.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,ADULT,1,0,60 to 64 years,X,Main Library,May,2016,z,email,True,2014,True,NaN
1,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN
2,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN
3,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN
4,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN