In [28]:
import urllib.request
import pandas as pd
import csv

In [29]:
csv = pd.read_csv(r"C:\Users\Rene\Desktop\Library_Usage_Liste.csv")

In [30]:
csv.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,ADULT,1092,761,60 to 64 years,M6,Mission,July,2016,p,phone,False,2003,False,9.0
1,0,ADULT,0,0,20 to 24 years,P1,Park,None,None,z,email,True,2014,False,5.0
2,0,ADULT,31,22,25 to 34 years,S7,Sunset,April,2016,z,email,True,2010,False,4.0
3,0,ADULT,0,0,45 to 54 years,P1,Park,None,None,a,print,False,2016,True,NaN
4,0,ADULT,0,0,25 to 34 years,X,Main Library,None,None,z,email,True,2015,False,3.0

In [24]:
csv.keys()

Index(['Patron Type Code', 'Patron Type Definition', 'Total Checkouts',
       'Total Renewals', 'Age Range', 'Home Library Code',
       'Home Library Definition', 'Circulation Active Month',
       'Circulation Active Year', 'Notice Preference Code',
       'Notice Preference Definition', 'Provided Email Address',
       'Year Patron Registered', 'Outside of County', 'Supervisor District'],
      dtype='object')

In [25]:
print(csv)

        Patron Type Code Patron Type Definition  Total Checkouts  \
0                      0                  ADULT             1092
1                      0                  ADULT                0
2                      0                  ADULT               31
3                      0                  ADULT                0
4                      0                  ADULT                0
5                      0                  ADULT              126
6                      3                 SENIOR                0
7                      0                  ADULT             3002
8                      0                  ADULT                4
9                      0                  ADULT               20
10                     0                  ADULT                3
11                     0                  ADULT              102
12                     0                  ADULT                0
13                     0                  ADULT               45
14                     0                  ADULT               88
15                     0                  ADULT               22
16                     0                  ADULT                1
17                     0                  ADULT                0
18                     0                  ADULT                5
19                     4                WELCOME                0
20                     0                  ADULT                0
21                     0                  ADULT                0
22                     0                  ADULT                1
23                     0                  ADULT                0
24                     0                  ADULT               12
25                     0                  ADULT                0
26                     0                  ADULT                0
27                     0                  ADULT               13
28                     0                  ADULT                0
29                     0                  ADULT                3
...                  ...                    ...              ...
423418                 3                 SENIOR                6
423419                 0                  ADULT                0
423420                 1               JUVENILE                5
423421                 2            YOUNG ADULT             1277
423422                 2            YOUNG ADULT             3914
423423                 0                  ADULT             2592
423424                 3                 SENIOR                0
423425                 1               JUVENILE               21
423426                 1               JUVENILE              373
423427                 1               JUVENILE               42
423428                 3                 SENIOR              425
423429                 1               JUVENILE                0
423430                 2            YOUNG ADULT               42
423431                 3                 SENIOR                0
423432                 2            YOUNG ADULT                0
423433                 4                WELCOME                0
423434                 1               JUVENILE               10
423435                 2            YOUNG ADULT               17
423436                16    DIGITAL ACCESS CARD                0
423437                 1               JUVENILE                0
423438                 0                  ADULT                0
423439                 1               JUVENILE                0
423440                 2            YOUNG ADULT               42
423441                 3                 SENIOR             1812
423442                 2            YOUNG ADULT              608
423443                 0                  ADULT              291
423444                 0                  ADULT               15
423445                 5                  STAFF              208
423446                 0                  ADULT               26
423447                 1               JUVENILE                0

        Total Renewals          Age Range Home Library Code  \
0                  761     60 to 64 years                M6
1                    0     20 to 24 years                P1
2                   22     25 to 34 years                S7
3                    0     45 to 54 years                P1
4                    0     25 to 34 years                 X
5                   11     45 to 54 years                M2
6                    0     65 to 74 years                C2
7                 1689     25 to 34 years                P5
8                    0     25 to 34 years                C2
9                    0     25 to 34 years                S7
10                   1     60 to 64 years                A5
11                  31     25 to 34 years                M6
12                   0     25 to 34 years                P7
13                  11     25 to 34 years                P3
14                  64     35 to 44 years                A5
15                   6     45 to 54 years                M2
16                   0     60 to 64 years                 X
17                   0     45 to 54 years                M4
18                   1     25 to 34 years                A5
19                   0     35 to 44 years                M6
20                   0     35 to 44 years                P1
21                   0     25 to 34 years                M4
22                   0     60 to 64 years                 X
23                   0     35 to 44 years                P1
24                   0     45 to 54 years                S7
25                   0     25 to 34 years                P7
26                   0     35 to 44 years                A5
27                  12     25 to 34 years                N6
28                   0     35 to 44 years                P1
29                   0     25 to 34 years                O7
...                ...                ...               ...
423418               1  75 years and over                R3
423419               0     60 to 64 years                E7
423420               0     10 to 19 years                R3
423421             642     10 to 19 years                S7
423422             359     10 to 19 years                P5
423423             487     10 to 19 years                I5
423424               0  75 years and over                E9
423425               0       0 to 9 years                O7
423426             216       0 to 9 years                M6
423427               1       0 to 9 years                 X
423428             381  75 years and over                 X
423429               0       0 to 9 years                N4
423430              21     10 to 19 years                 X
423431               0  75 years and over                 X
423432               0     10 to 19 years                 X
423433               0     45 to 54 years                 X
423434               0       0 to 9 years                V3
423435               0     10 to 19 years                B2
423436               0     10 to 19 years                P1
423437               0       0 to 9 years                W4
423438               0     10 to 19 years                W4
423439               0       0 to 9 years                N4
423440              53     10 to 19 years                M4
423441               0  75 years and over                C2
423442             364     10 to 19 years                S7
423443              13     10 to 19 years                P5
423444              11     60 to 64 years                M8
423445              58       0 to 9 years                B4
423446               0     10 to 19 years                M6
423447               0       0 to 9 years                E7

                   Home Library Definition Circulation Active Month  \
0                                  Mission                     July
1                                     Park                     None
2                                   Sunset                    April
3                                     Park                     None
4                             Main Library                     None
5                                   Marina                  January
6                                Chinatown                     None
7                                  Portola                     July
8                                Chinatown                     July
9                                   Sunset                     June
10                                    Anza                     June
11                                 Mission                     June
12                                 Potrero                     None
13                                Parkside                      May
14                                    Anza                     July
15                                  Marina                      May
16                            Main Library                      May
17                                  Merced                     None
18                                    Anza                  January
19                                 Mission                     None
20                                    Park                     None
21                                  Merced                     None
22                            Main Library                     June
23                                    Park                     None
24                                  Sunset                     June
25                                 Potrero                     None
26                                    Anza                     None
27                             North Beach                 February
28                                    Park                     None
29                                  Ortega                   August
...                                    ...                      ...
423418                            Richmond                September
423419  Eureka Valley/Harvey Milk Memorial                     None
423420                            Richmond                     July
423421                              Sunset                     July
423422                             Portola                     July
423423                           Ingleside                  January
423424                           Excelsior                     None
423425                              Ortega                September
423426                             Mission                  October
423427                        Main Library                     July
423428                        Main Library                     July
423429              Noe Valley/Sally Brunn                     None
423430                        Main Library                September
423431                        Main Library                     None
423432                        Main Library                     None
423433                        Main Library                     None
423434                   Visitacion Valley                September
423435         Bayview/Linda Brooks-Burton                      May
423436                                Park                     None
423437                    Western Addition                     None
423438                    Western Addition                     None
423439              Noe Valley/Sally Brunn                     None
423440                              Merced                     June
423441                           Chinatown                     July
423442                              Sunset                     July
423443                             Portola                    March
423444                         Mission Bay                     July
423445                      Bernal Heights                     July
423446                             Mission                    April
423447  Eureka Valley/Harvey Milk Memorial                     None

       Circulation Active Year Notice Preference Code  \
0                         2016                      p
1                         None                      z
2                         2016                      z
3                         None                      a
4                         None                      z
5                         2016                      z
6                         None                      z
7                         2016                      p
8                         2014                      p
9                         2015                      z
10                        2016                      z
11                        2012                      z
12                        None                      z
13                        2016                      z
14                        2016                      z
15                        2016                      z
16                        2016                      z
17                        None                      z
18                        2012                      z
19                        None                      z
20                        None                      z
21                        None                      z
22                        2013                      z
23                        None                      z
24                        2014                      z
25                        None                      z
26                        None                      z
27                        2014                      z
28                        None                      z
29                        2015                      z
...                        ...                    ...
423418                    2015                      p
423419                    None                      p
423420                    2015                      z
423421                    2016                      p
423422                    2016                      p
423423                    2016                      p
423424                    None                      p
423425                    2015                      z
423426                    2014                      z
423427                    2016                      z
423428                    2016                      p
423429                    None                      z
423430                    2013                      z
423431                    None                      z
423432                    None                      a
423433                    None                      z
423434                    2015                      p
423435                    2015                      z
423436                    None                      z
423437                    None                      z
423438                    None                      z
423439                    None                      z
423440                    2014                      p
423441                    2016                      p
423442                    2016                      z
423443                    2015                      p
423444                    2016                      z
423445                    2016                      z
423446                    2015                      z
423447                    None                      a

       Notice Preference Definition  Provided Email Address  \
0                             phone                   False
1                             email                    True
2                             email                    True
3                             print                   False
4                             email                    True
5                             email                    True
6                             email                    True
7                             phone                    True
8                             phone                    True
9                             email                    True
10                            email                    True
11                            email                    True
12                            email                    True
13                            email                    True
14                            email                    True
15                            email                    True
16                            email                    True
17                            email                    True
18                            email                    True
19                            email                    True
20                            email                    True
21                            email                    True
22                            email                    True
23                            email                    True
24                            email                    True
25                            email                    True
26                            email                    True
27                            email                    True
28                            email                    True
29                            email                    True
...                             ...                     ...
423418                        phone                   False
423419                        phone                   False
423420                        email                    True
423421                        phone                   False
423422                        phone                   False
423423                        phone                   False
423424                        phone                   False
423425                        email                    True
423426                        email                    True
423427                        email                    True
423428                        phone                   False
423429                        email                    True
423430                        email                    True
423431                        email                    True
423432                        print                   False
423433                        email                    True
423434                        phone                   False
423435                        email                    True
423436                        email                    True
423437                        email                    True
423438                        email                    True
423439                        email                    True
423440                        phone                   False
423441                        phone                   False
423442                        email                    True
423443                        phone                   False
423444                        email                    True
423445                        email                    True
423446                        email                    True
423447                        print                   False

        Year Patron Registered  Outside of County  Supervisor District
0                         2003              False                  9.0
1                         2014              False                  5.0
2                         2010              False                  4.0
3                         2016               True                  NaN
4                         2015              False                  3.0
5                         2003              False                  2.0
6                         2015               True                  NaN
7                         2004              False                  9.0
8                         2014              False                  5.0
9                         2011              False                  7.0
10                        2013              False                  NaN
11                        2009              False                  9.0

In [26]:
#Fragestellung 1, Thema Seniorenaktiviät: Zeige mir alle Benutzer ab 75 Jahren die Ihren Bibliotheksausweis erneuert haben.

In [75]:
Senior = csv[csv["Age Range"] == "75 years and over"]
Bibliotheksausweis_Erneuerung = csv[csv["Total Renewals"] >= 1]
Senioren_Verlängerungen = pd.merge(Senior, Bibliotheksausweis_Erneuerung)
#Senioren_Verlängerungen.head()
print(Senioren_Verlängerungen)

      Patron Type Code Patron Type Definition  Total Checkouts  \
0                    3                 SENIOR              838
1                    3                 SENIOR               65
2                    3                 SENIOR              122
3                    3                 SENIOR              222
4                    3                 SENIOR              487
5                    3                 SENIOR                7
6                    3                 SENIOR               43
7                    3                 SENIOR              662
8                    3                 SENIOR               42
9                    3                 SENIOR              203
10                   3                 SENIOR              172
11                   3                 SENIOR              408
12                   3                 SENIOR              675
13                   3                 SENIOR                1
14                   3                 SENIOR              796
15                   3                 SENIOR              275
16                   3                 SENIOR              398
17                   3                 SENIOR              454
18                   3                 SENIOR               48
19                   3                 SENIOR             2015
20                   3                 SENIOR              189
21                  15           TEACHER CARD              131
22                   3                 SENIOR              522
23                   3                 SENIOR              220
24                   3                 SENIOR              167
25                   3                 SENIOR              247
26                   3                 SENIOR              275
27                   3                 SENIOR                2
28                   3                 SENIOR             3533
29                   3                 SENIOR               73
...                ...                    ...              ...
9833                 3                 SENIOR              643
9834               103         AT USER SENIOR              497
9835                 3                 SENIOR                3
9836                 3                 SENIOR                9
9837                 3                 SENIOR              569
9838                 3                 SENIOR              569
9839                 3                 SENIOR              109
9840                 3                 SENIOR                6
9841                 3                 SENIOR              604
9842                 3                 SENIOR             1406
9843                 3                 SENIOR              550
9844                 3                 SENIOR              460
9845                 9                SPECIAL               37
9846                 3                 SENIOR               16
9847                 3                 SENIOR              178
9848                 3                 SENIOR              879
9849                 3                 SENIOR               16
9850                 3                 SENIOR              334
9851                 3                 SENIOR              733
9852                 3                 SENIOR                5
9853                 3                 SENIOR                1
9854                 3                 SENIOR              638
9855                 3                 SENIOR             2893
9856                 3                 SENIOR                1
9857                 9                SPECIAL               31
9858                 3                 SENIOR               25
9859                 3                 SENIOR              458
9860                 3                 SENIOR              280
9861                 3                 SENIOR                6
9862                 3                 SENIOR              425

      Total Renewals          Age Range Home Library Code  \
0                415  75 years and over                N6
1                 15  75 years and over                E9
2                  7  75 years and over                P9
3                 16  75 years and over                P7
4                 34  75 years and over                R3
5                  3  75 years and over                P1
6                 24  75 years and over                P1
7                 66  75 years and over                G4
8                 28  75 years and over                 X
9                 57  75 years and over                E9
10                59  75 years and over                R3
11               197  75 years and over                W2
12                33  75 years and over                P1
13                 2  75 years and over                M2
14               545  75 years and over                W4
15                37  75 years and over                 X
16               136  75 years and over                N6
17                80  75 years and over                C2
18                 7  75 years and over                P3
19                30  75 years and over                W2
20                69  75 years and over                R3
21                15  75 years and over                P1
22                45  75 years and over                E9
23                27  75 years and over                E9
24                18  75 years and over                O7
25                75  75 years and over                P3
26                50  75 years and over                E7
27                 1  75 years and over                S7
28               148  75 years and over                 X
29                 1  75 years and over                E7
...              ...                ...               ...
9833             330  75 years and over                M4
9834             164  75 years and over                R3
9835               1  75 years and over                M4
9836               2  75 years and over                 X
9837              52  75 years and over                R3
9838              93  75 years and over                 X
9839              28  75 years and over                 X
9840               1  75 years and over                M4
9841             112  75 years and over                 X
9842              86  75 years and over                R3
9843               6  75 years and over                O7
9844              15  75 years and over                M4
9845               5  75 years and over               YLW
9846               3  75 years and over                A5
9847               1  75 years and over                A5
9848              18  75 years and over                 X
9849               2  75 years and over                R3
9850              13  75 years and over                C2
9851             943  75 years and over                 X
9852              11  75 years and over                W4
9853               1  75 years and over                P9
9854             204  75 years and over                O7
9855              54  75 years and over                C2
9856               1  75 years and over                N6
9857              15  75 years and over              XFFL
9858              34  75 years and over                 X
9859             129  75 years and over                E9
9860              27  75 years and over                 X
9861               1  75 years and over                R3
9862             381  75 years and over                 X

                 Home Library Definition Circulation Active Month  \
0                            North Beach                     July
1                              Excelsior                     June
2                               Presidio                    April
3                                Potrero                     July
4                               Richmond                      May
5                                   Park                      May
6                                   Park                  January
7                              Glen Park                 February
8                           Main Library                September
9                              Excelsior                     June
10                              Richmond                     July
11                           West Portal                 February
12                                  Park                     July
13                                Marina                      May
14                      Western Addition                     July
15                          Main Library                    April
16                           North Beach                  January
17                             Chinatown                   August
18                              Parkside                 December
19                           West Portal                     July
20                              Richmond                     June
21                                  Park                     July
22                             Excelsior                September
23                             Excelsior                    April
24                                Ortega                    April
25                              Parkside                     July
26    Eureka Valley/Harvey Milk Memorial                     July
27                                Sunset                    April
28                          Main Library                     June
29    Eureka Valley/Harvey Milk Memorial                  October
...                                  ...                      ...
9833                              Merced                     June
9834                            Richmond                 December
9835                              Merced                 November
9836                        Main Library                      May
9837                            Richmond                     July
9838                        Main Library                    April
9839                        Main Library                     June
9840                              Merced                     July
9841                        Main Library                     June
9842                            Richmond                     July
9843                              Ortega                    March
9844                              Merced                     July
9845                   Library on Wheels                     July
9846                                Anza                   August
9847                                Anza                     July
9848                        Main Library                     July
9849                            Richmond                September
9850                           Chinatown                September
9851                        Main Library                     July
9852                    Western Addition                   August
9853                            Presidio                    April
9854                              Ortega                     June
9855                           Chinatown                     July
9856                         North Beach                     July
9857                             Unknown                   August
9858                        Main Library                      May
9859                           Excelsior                     June
9860                        Main Library                     July
9861                            Richmond                September
9862                        Main Library                     July

     Circulation Active Year Notice Preference Code  \
0                       2016                      z
1                       2016                      p
2                       2014                      z
3                       2016                      p
4                       2015                      z
5                       2010                      p
6                       2016                      z
7                       2016                      z
8                       2012                      p
9                       2016                      p
10                      2016                      z
11                      2016                      z
12                      2016                      z
13                      2010                      p
14                      2016                      p
15                      2014                      z
16                      2016                      z
17                      2015                      a
18                      2015                      a
19                      2016                      z
20                      2016                      z
21                      2016                      z
22                      2014                      p
23                      2014                      z
24                      2016                      z
25                      2016                      z
26                      2016                      z
27                      2016                      z
28                      2016                      z
29                      2015                      z
...                      ...                    ...
9833                    2016                      z
9834                    2013                      p
9835                    2010                      a
9836                    2007                      z
9837                    2016                      p
9838                    2015                      z
9839                    2016                      p
9840                    2014                      p
9841                    2016                      z
9842                    2016                      p
9843                    2016                      p
9844                    2016                      z
9845                    2015                      a
9846                    2015                      a
9847                    2016                      a
9848                    2016                      a
9849                    2012                      a
9850                    2013                      a
9851                    2016                      p
9852                    2014                      z
9853                    2015                      z
9854                    2016                      p
9855                    2016                      a
9856                    2016                      z
9857                    2014                      a
9858                    2016                      z
9859                    2016                      z
9860                    2016                      z
9861                    2015                      p
9862                    2016                      p

     Notice Preference Definition  Provided Email Address  \
0                           email                    True
1                           phone                   False
2                           email                    True
3                           phone                    True
4                           email                    True
5                           phone                   False
6                           email                    True
7                           email                    True
8                           phone                   False
9                           phone                   False
10                          email                    True
11                          email                    True
12                          email                    True
13                          phone                   False
14                          phone                   False
15                          email                    True
16                          email                    True
17                          print                   False
18                          print                   False
19                          email                    True
20                          email                    True
21                          email                    True
22                          phone                   False
23                          email                    True
24                          email                    True
25                          email                    True
26                          email                    True
27                          email                    True
28                          email                    True
29                          email                    True
...                           ...                     ...
9833                        email                    True
9834                        phone                   False
9835                        print                   False
9836                        email                    True
9837                        phone                   False
9838                        email                    True
9839                        phone                   False
9840                        phone                   False
9841                        email                    True
9842                        phone                   False
9843                        phone                   False
9844                        email                    True
9845                        print                   False
9846                        print                   False
9847                        print                   False
9848                        print                   False
9849                        print                   False
9850                        print                   False
9851                        phone                   False
9852                        email                    True
9853                        email                    True
9854                        phone                   False
9855                        print                   False
9856                        email                    True
9857                        print                   False
9858                        email                    True
9859                        email                    True
9860                        email                    True
9861                        phone                   False
9862                        phone                   False

      Year Patron Registered  Outside of County  Supervisor District
0                       2003              False                  NaN
1                       2003              False                 11.0
2                       2011              False                  2.0
3                       2003              False                 10.0
4                       2003              False                  2.0
5                       2003              False                  NaN
6                       2003              False                  5.0
7                       2008              False                  8.0
8                       2004               True                  NaN
9                       2006              False                 11.0
10                      2003              False                  1.0
11                      2004              False                  7.0
12                      2003              False                  1.0
13                      2007              False                  2.0
14                      2003              False                  NaN
15                      2003              False                  4.0
16                      2003              False                  3.0
17                      2003              False                  3.0
18                      2014              False                  7.0
19                      2003              False                  4.0
20                      2003              False                  8.0

In [57]:
#Fragestellung 2 Thema Standortanaylse: Wie viele Ausleihen gab es von Nutzern in der Zentralbibliothek?

In [72]:
Zentralbibliothek = csv[csv["Home Library Definition"] == "Main Library"]
Ausleihen = csv[csv["Total Checkouts"] >= 1]
Zentralbibliothek_Ausleihen = pd.merge(Zentralbibliothek, Ausleihen)
Zentralbibliothek_Ausleihen.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,ADULT,1,0,60 to 64 years,X,Main Library,May,2016,z,email,True,2014,True,NaN
1,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN
2,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN
3,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN
4,0,ADULT,1,0,60 to 64 years,X,Main Library,June,2013,z,email,True,2013,True,NaN